Clear message when missing FIREBASE_TOKEN in CI settings

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,6 +53,14 @@ jobs:
         run: |
           set -o pipefail
 
+          # Throw a clear error if FIREBASE_TOKEN is not set
+          if [ ! -z "$FIREBASE_TOKEN" ];
+            then
+              echo "FIREBASE_TOKEN environment variable is required to load project configs"
+              exit 1
+          fi
+
+          # Get Branch name by stripping from end of GITHUB_REF
           gitBranch=${GITHUB_REF##*/}
 
           # Find the config associated to the firebase project in .firebaserc (falling back to default)
